---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.11.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  install:
    crds: Create
    createNamespace: true
  interval: 1m0s
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
  values:
    storageClass:
      create: true
      name: nfs-csi
      parameters:
        server: diskstation.${homedomain:=undefined}
        share: /volume1/kubernetes-nfs/
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      mountOptions:
        - nfsvers=4.1