apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-creds
  namespace: openwebui
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-creds
    template:
      data:
        access-key: "{{ .accessKeyID | toString }}"
        secret-key: "{{ .secretAccessKey | toString }}"
        oauth-client-secret: "{{ .clientSecret | toString }}"
  data:
  - secretKey: accessKeyID
    remoteRef:
      key: obc-flux-open-webui-key-id
      property: k3s
  - secretKey: secretAccessKey
    remoteRef:
      key: obc-flux-open-webui-secret-key
      property: k3s
  - secretKey: clientSecret
    remoteRef:
      key: openwebui-client-secret
      property: authentik