---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner-secret
  namespace: gitea
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: gitea-runner-secret
    template:
      data:
        token: "{{ .token | toString }}"
  data:
  - secretKey: token
    remoteRef:
      key: gitea-runner-token
      property: k3s