apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-status
  namespace: flux-system
spec:
  type: github
  address: https://github.com/SimonStiil/k3s-flux
  secretRef:
    name: github-flux-notifications-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github-status
  namespace: flux-system
spec:
  providerRef:
    name: github-status
  eventSources:
  - kind: Kustomization
    name: cert-manager
  - kind: Kustomization
    name: csi-driver-nfs
  - kind: Kustomization
    name: external-secrets
  - kind: Kustomization
    name: flux-system
  - kind: Kustomization
    name: flux-webhook