# clusters/production/flux-system/helmrelease-nextcloud.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: "8.9.1"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  targetNamespace: nextcloud
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      flavor: apache #fpm-alpine
    
    replicaCount: 1
    
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
        traefik.ingress.kubernetes.io/router.tls: "true"  
      hosts:
        - host: cloud.${topleveldomain}
          paths:
            - path: /
              pathType: ImplementationSpecific
    
    nextcloud:
      host: cloud.${topleveldomain}
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'allow_local_remote_servers' => true,
            'overwriteprotocol' => 'https'
          );
        oidc.config.php: |-
          <?php
          $CONFIG = array (
            'allow_user_to_change_display_name' => false,
            'lost_password_link' => 'disabled',
            'oidc_login_provider_url' => 'https://auth.${topleveldomain:=undefined}',
            'oidc_login_client_id' => 'nextcloud',
            'oidc_login_client_secret' => '${nextcloudoidcclientsecret}',
            'oidc_login_auto_redirect' => false,
            'oidc_login_end_session_redirect' => false,
            'oidc_login_button_text' => 'Log in with Authelia',
            'oidc_login_hide_password_form' => false,
            'oidc_login_use_id_token' => false,
            'oidc_login_attributes' => array (
                'id' => 'preferred_username',
                'name' => 'name',
                'mail' => 'email',
                'groups' => 'groups',
                'is_admin' => 'is_nextcloud_admin',
            ),
            'oidc_login_default_group' => 'oidc',
            'oidc_login_use_external_storage' => false,
            'oidc_login_scope' => 'openid profile email groups nextcloud_userinfo',
            'oidc_login_proxy_ldap' => false,
            'oidc_login_disable_registration' => false,
            'oidc_login_redir_fallback' => false,
            'oidc_login_tls_verify' => true,
            'oidc_create_groups' => true,
            'oidc_login_webdav_enabled' => false,
            'oidc_login_password_authentication' => false,
            'oidc_login_public_key_caching_time' => 86400,
            'oidc_login_min_time_between_jwks_requests' => 10,
            'oidc_login_well_known_caching_time' => 86400,
            'oidc_login_update_avatar' => true,
            'oidc_login_code_challenge_method' => 'S256'
          );
    internalDatabase:
      enabled: false
    
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-db-rw
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db-credentials
        usernameKey: username
        passwordKey: password
    
    externalRedis:
      enabled: true
      host: "nextcloud-valkey-nextcloud"
      port: "6379"
      existingSecret:
        enabled: true
        secretName: valkey
        passwordKey: default
    redis:
      enabled: false
      auth:
        enabled: true
        password: your-redis-password
      master:
        persistence:
          storageClass: local-path
          size: 2Gi
      architecture: standalone
    cronjob:
      enabled: true
      
    collabora:
      enabled: true
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
      ingress:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
          traefik.ingress.kubernetes.io/router.tls: "true"    
        hosts:
          - host: collabora.${topleveldomain}
            paths:
              - path: /
                pathType: ImplementationSpecific
    persistence:
      enabled: true
      size: 100Gi
      storageClass: nfs-csi
