apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud-admin
    template:
      type: Opaque
      data:
        username: admin
        password: "{{ .password | toString }}"
  data:
    - secretKey: password
      remoteRef:
        key: nextcloud-admin-password
        property: k3s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db-credentials
  namespace: nextcloud
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud-db-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: nextcloud
        password: "{{ .password | toString }}"
  data:
    - secretKey: password
      remoteRef:
        key: nextcloud-db-password
        property: k3s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: email-secret
  namespace: nextcloud
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: email-secret
    template:
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
  data:
  - secretKey: username
    remoteRef:
      key: robot-email-username
  - secretKey: password
    remoteRef:
      key: robot-email-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey
  namespace: nextcloud
spec:
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: valkey
    creationPolicy: Owner
    template:
      data:
        default: "{{ .valkeyPassword | toString }}"
        nextcloud: "{{ .valkeyPassword | toString }}"
  data:
  - secretKey: valkeyPassword
    remoteRef:
      key: nextcloud-valkey-password
      property: k3s
---