# clusters/production/flux-system/helmrelease-nextcloud.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: "8.8.1"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  targetNamespace: nextcloud
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      flavor: apache #fpm-alpine
    
    replicaCount: 1
    
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: cloud.${topleveldomain}
    
    nextcloud:
      host: cloud.${topleveldomain}
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
    
    internalDatabase:
      enabled: false
    
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-db-rw
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db-credentials
        usernameKey: username
        passwordKey: password
    
    redis:
      enabled: true
      auth:
        enabled: true
        password: your-redis-password
      master:
        persistence:
          storageClass: local-path
          size: 2Gi
      architecture: standalone
    cronjob:
      enabled: true
    
    persistence:
      enabled: true
      size: 100Gi
      storageClass: nfs-csi
