# clusters/production/nextcloud/cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  instances: 1
  
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
  
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-db-credentials
  
  storage:
    size: 10Gi
    storageClass: local-path