---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jenkins.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.external-secrets.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pascaliske
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.pascaliske.dev
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  url: https://traefik.github.io/charts
--- 
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rocm-gpu-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://rocm.github.io/gpu-operator
--- 
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rocm-device-metrics-exporter
  namespace: flux-system
spec:
  interval: 1h
  url: https://rocm.github.io/device-metrics-exporter
--- 
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: otwld
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.otwld.com
--- 
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jupyterhub 
  namespace: flux-system
spec:
  interval: 1h
  url: https://hub.jupyter.org/helm-chart/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.openwebui.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: meilisearch
  namespace: flux-system
spec:
  interval: 1h
  url: https://meilisearch.github.io/meilisearch-kubernetes
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: valkey
  namespace: flux-system
spec:
  interval: 1h
  url: https://valkey.io/valkey-helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community-oci
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 1h
  url: https://nextcloud.github.io/helm/
---