---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golang-cache
  namespace: jenkins
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golang-prgs
  namespace: jenkins
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---