apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-pat-secret
  namespace: jenkins
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: gitea-pat-secret
    template:
      metadata:
        labels:
          "jenkins.io/credentials-scope": "global"
          "jenkins.io/credentials-type": "giteaPAT"
        annotations:
          "jenkins.io/credentials-description": "Jenkins gitea Account Token"
      data:
        token: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      key: jenkins-gitea-pat