apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
  namespace: jenkins
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: oidc-secret
    template:
      data:
        secret: "{{ .secret | toString }}"
  data:
  - secretKey: secret
    remoteRef:
      key: jenkins-oidc-secret