---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ollama
      version: "1.32.0"
      sourceRef:
        kind: HelmRepository
        name: otwld 
        namespace: flux-system
  install:
    crds: Create
    createNamespace: true
  interval: 15m0s
  targetNamespace: ollama
  upgrade:
    crds: CreateReplace
  values:
    ollama:
      gpu:
        # -- Enable GPU integration
        enabled: false
        # -- GPU type: 'nvidia' or 'amd'
        type: 'amd'
    
        # -- Specify the number of GPU to 1
        number: 1
    persistentVolume:
      enabled: true
      size: 200Gi
      storageClass: local-path
    volumes:
      - name: dev-dri
        hostPath:
          path: /dev/dri
      - name: dev-kfd
        hostPath:
          path: /dev/kfd
    volumeMounts:
      - name: dev-dri
        mountPath: /dev/dri
      - name: dev-kfd
        mountPath: /dev/kfd
    podSecurityContext:
      supplementalGroups: [27, 44, 993] #sudo, video, render groups
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/ollama: "unconfined"