---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ollama
      version: "1.35.0"
      sourceRef:
        kind: HelmRepository
        name: otwld 
        namespace: flux-system
  install:
    crds: Create
    createNamespace: true
  interval: 15m0s
  targetNamespace: ollama
  upgrade:
    crds: CreateReplace
  values:
#    knative:
#      enabled: true
    image:
      tag: 0.12.5-rocm
    ollama:
      gpu:
        # -- Enable GPU integration
        enabled: false
        # -- GPU type: 'nvidia' or 'amd'
        type: 'amd'
    
        # -- Specify the number of GPU to 1
        number: 1
    persistentVolume:
      enabled: true
      size: 200Gi
      storageClass: local-path
    volumes:
      - name: dev-dri
        hostPath:
          path: /dev/dri
      - name: dev-kfd
        hostPath:
          path: /dev/kfd
    volumeMounts:
      - name: dev-dri
        mountPath: /dev/dri
      - name: dev-kfd
        mountPath: /dev/kfd
    podSecurityContext:
      supplementalGroups: [27, 44, 993] #sudo, video, render groups
    securityContext:
      privileged: true
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/ollama: "unconfined"

    # Configure the ingress resource that allows you to access the
    ingress:
      # -- Enable ingress controller resource
      enabled: true

      # -- IngressClass that will be used to implement the Ingress (Kubernetes 1.18+)
      className: "traefik"

      # -- Additional annotations for the Ingress resource.
      annotations: 
        traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: stiil-issuer

      # The list of hostnames to be covered with this ingress record.
      hosts:
        - host: ollama.k3s.${homedomain:=undefined}
          paths:
            - path: /
              pathType: Prefix
      # --  The tls configuration for hostnames to be covered with this ingress record.
      tls: 
        - hosts:
          - ollama.k3s.${homedomain:=undefined}
          secretName: ollama-home-cert
    