---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ollama
      version: "1.32.0"
      sourceRef:
        kind: HelmRepository
        name: otwld 
        namespace: flux-system
  install:
    crds: Create
    createNamespace: true
  interval: 15m0s
  targetNamespace: ollama
  upgrade:
    crds: CreateReplace
  values:
    ollama:
      gpu:
        # -- Enable GPU integration
        enabled: true
        # -- GPU type: 'nvidia' or 'amd'
        type: 'amd'
    
        # -- Specify the number of GPU to 1
        number: 1
    persistentVolume:
      enabled: true
      size: 200Gi
      storageClass: local-path