apiVersion: v1
kind: Namespace
metadata:
  name: jupyterhub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-devops
  namespace: jupyterhub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyterhub-devops-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: jupyterhub-devops
    namespace: jupyterhub